<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-I31QPDV" failures="1" tests="8" name="testNGclasses.ServiceAccount" time="222.071" errors="0" timestamp="2021-08-11T17:58:40 UYT" skipped="0">
  <testcase classname="testNGclasses.ServiceAccount" name="tcPositiveCreateFullAccountRecord" time="36.673"/>
  <system-out/>
  <testcase classname="testNGclasses.ServiceAccount" name="tcNegativeVoidAccountName" time="28.489"/>
  <system-out/>
  <testcase classname="testNGclasses.ServiceAccount" name="tcModifyAccountRecordValuesRUT" time="27.671">
    <failure message="expected [Yes] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Yes] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testNGclasses.ServiceAccount.userValidatesModifiedValues(ServiceAccount.java:310)
at testNGclasses.ServiceAccount.tcModifyAccountRecordValuesRUT(ServiceAccount.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tcModifyAccountRecordValuesRUT -->
  <system-out/>
  <testcase classname="testNGclasses.ServiceAccount" name="tcNegativeInvalidEmployeeValue" time="25.551"/>
  <system-out/>
  <testcase classname="testNGclasses.ServiceAccount" name="tcPositiveMultipleAccounts" time="25.327"/>
  <system-out/>
  <testcase classname="testNGclasses.ServiceAccount" name="tcPositiveMultipleAccounts" time="24.148"/>
  <system-out/>
  <testcase classname="testNGclasses.ServiceAccount" name="tcPositiveMultipleAccounts" time="24.092"/>
  <system-out/>
  <testcase classname="testNGclasses.ServiceAccount" name="tcPositiveMultipleAccounts" time="30.120"/>
  <system-out/>
</testsuite> <!-- testNGclasses.ServiceAccount -->
